# Common configuration.
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.0
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - app/models/ability.rb
    - test/**/*
    - db/**/*
    - config/routes.rb
    - app/**/_archive/**/*
    - app/**/*_archive/**/*
    - app/**/*v0/**/*
    - app/**/*archive*
    - app/models/*_detail.rb


Lint/AmbiguousBlockAssociation:
  Exclude:
    - app/models/**/*.rb


#######################################################
#   LAYOUT NAMESPACE


Layout/AlignParameters:
  EnforcedStyle: with_first_parameter


Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: false
  NumberOfEmptyLines: [2, 3]

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/EmptyLines:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false


#######################################################
#   METRICS NAMESPACE

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*

Metrics/ClassLength:
  CountComments: false
  Max: 250

Metrics/LineLength:
  Max: 99
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoredPatterns:
    - '=>'
    - '->'
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Max: 25


#######################################################
#   STYLE NAMESPACE


Style/Lambda:
  Exclude:
    - app/models/**/*.rb

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MixinGrouping:
  EnforcedStyle: grouped

Style/MutableConstant:
  Exclude:
    - config/initializers/app_version.rb

Style/VariableNumber:
  EnforcedStyle: snake_case

Style/WordArray:
  EnforcedStyle: brackets
  Exclude:
    - config/application.rb


#######################################################
#   RAILS NAMESPACE


Rails/Output:
  Exclude:
    - app/services/cafes/event_relocator.rb
    - app/services/cafes/location_cafe_importer.rb
    - app/services/event_import/bit_importer.rb
    - app/services/event_import/fundraising_importer.rb
